### ISSUE TITLE
Logo Renew Proposals 

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#1]
Creo que el logo que se adapta mejor a esta empresa es esta propuesta;

DESCRIPCION DEL LOGO:

- Se conserva la ola del logo anterior y los colores, se juega con la conexión en este caso entre la empresa y el cliente, diseño con lineas finas

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/abf3b60b-c0c6-4360-a114-cac037364456)

- Esbozo inicial

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/420509ec-ea94-49f0-b1a8-f85a1265440b)

**Comment by 1987elo** [comment]
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/420509ec-ea94-49f0-b1a8-f85a1265440b)

**Comment by 1987elo** [comment]
Hola @vicktorinox & @ajsb85 
Estas son tres propuestas de logo para darle un aire mas innovador:


![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/f7ff267e-1317-4a82-ac1b-31f6032d5648)
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/1a8187e4-49b5-4ceb-99c9-3b819d32071a)
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/2c49de2c-6fd0-47f4-b1d9-549dfd328b3f)

Saludos.

**Comment by 1987elo** [comment]
adjunto 3 propuestas de logo para darle un aire mas innovador

**Comment by 1987elo** [comment]
@ajsb85 como hemos hablado 3 propuestas de logo a revisar, aunque voy a seguir trabajando con el anterior

**Comment by vicktorinox** [comment]
@1987elo sabes de los 3 logos que propones me gusta el primero de arriba hacia abajo en el orden que se muestra, tiene un toque de haberse hecho a tu mano, saludos.
