### ISSUE TITLE
Stationery

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#10]
papeleria para BBI 

PAPEL DE CARTA:

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/47471994-5c0e-4eeb-9e59-41b8ce240ee1)

SOBRE:

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/859478e3-fbdd-4349-ae31-fe54a659c317)

TARJETA:

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/7e324c6e-d58e-4ba7-a7ea-0edbf5d1658e)

**Comment by vicktorinox** [comment]
@1987elo de nuevo todo te quedo super te brindo una taza de cafe cuando quieras, saludos desde el otro lado del atlántico.
