### ISSUE TITLE
Briefing

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#2]
Nombre de la empresa: 
Big Blue Innova

Propietario:
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/fcef9f9d-050c-4b33-919b-7e855b2c4957)

Dirección:
Av. Cloroformo Valenzuela 760 - Región del Maule - Chile

Pagina Web:
bigblueinnova.com

Logo actual:
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/47fc02e7-981d-4acd-b622-5659a731b2a7)

Paleta de colores de logo:
Main blue     #044f89
Secunday blue #1094f9

El porque de los colores:
Big Blue Innova ha querido rendir homenaje al mar, ofreciendo así los colores y las olas que presenta el logotipo

Funcion de la empresa:
Assessoramiento, configuración y re-diseño de cualquier contenido digital adaptable, creación digital y e-learning, entre otros

Nuevos proyectos:
Dar soporte al servicio pos-venda en colaboración con otras empresas, instalando así aplicaciones adecuadas al soporte, ya sea telefónicamente, con programas de conexión remota, etc.
Diseño y creación de nuevos productos, creando un datasheet de estos y vendiendo al distribuidor con un mínimo de unidades

Que és:
Empresa marca propia de firechip fundada en Chile, con mas de 20 años de experiencia en el sector y consta un distribuidor en E.E.U.U.

como se define:
Como un pequeño gigante que aposta por producto local y respeto al medioambiente

A que publico quiere llegar: 
A todo aquel que necesite soporte para poner al dia sus empresas de los avances tecnológicos

que ventajas tiene?
puede trabajar a distancia en cualquier parte y consta de un equipo humano capacitado con todos los idiomas

**Comment by 1987elo** [comment]
@ajsb85 Hola Alexander era para la revisión de briefing, espero haber entendido bien el concepto de la empresa

**Comment by vicktorinox** [comment]
🤝💖 @1987elo elo elo elo fue bueno tu análisis aplausos cordiales, Alex me parece super bien todo.
