### ISSUE TITLE
Contra-briefing

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#3]
**Informe de contra-briefing basado en sitio web**

Objetivos del proyecto: 
impulsar el negocio, dar mayor visibilidad y rentabilidad

- Alcance del proyecto:
se tendría que estipular los paises a los que se desea llegar para potenciar el marketing en ellos, así mismo proporcionar un menú de idiomas.

- Descripción del producto:
Són descripciones muy generales, habría de detallar más el producto, nuestro trabajo, hasta donde llegamos y las herramientas que le vamos a proporcional al cliente, igualmente separar bien cada trabajo de los que hacemos, organizado por menús desplegables.
Explicar el proceso desde la primera toma de contacto al producto final.
Así como ofrecerle al cliente nuestro soporte vía control remoto o telefónica ya que estamos hablando que todo es a distancia, tanto en los primeros tratos como durante el proceso y también garantizar nuestro servicio pos-venta

- Plazo:
detallar los plazos con los que trabajamos para dar confianza al cliente de nuestro compromiso, asegurar unos plazos máximos para garantizar que no se va a demorar

- Presupuesto:
indicar que nuestros proyectos pueden ser asequibles para todo tipo de negocio, desde el autónomo a pequeñas, medianas y grandes empresas. si es necesario estipular precios para cada categoría
Para impulsar el negocio y darse a conocer se podría proponer ofertas marcadas por las estaciones del año y proyectar-las en las principales plataformas; instagram, facebook, etc. y hacer publicaciones diarias para conseguir la mayor visibilidad posible

- Equipo:
dar visibilidad al equipo humano que va a trabajar en ello es importante, una presentación con foto de cada miembro ayudaría a dar confianza al publico objetivo
También foto de nuestras instalaciones
  
- Diseño y creatividad:
el diseño tiene un aire moderno pero es poco innovador por el producto que estamos vendiendo, sería necesario poner mas fotos, un diseño más tecnológico y arriesgado e incorporar objetos flash, hay que tener en cuenta que nuestra propia web será nuestra tarjeta de presentación, tenemos que mostrar al publico todo lo que somos capaces de hacer por su empresa, tecnológicamente hablando

- Logo:
El logo se podría modernizar un poco, se tiene que definir que el logo no puede estar sobre fondo oscuro puesto que las letras principales BBI que presentan un color azul más oscuro casi no se aprecian, para ello se tendría que redactar un manual de identidad para estipular de qué colores tendrían que ser las letras en estos casos.

- Plan de marketing:
hacer tarjetas de visita, banners para las webs que hemos creado (ofreciendo un pequeño dto.en nuestro trabajo) y potenciando la temática marina que hemos elegido para nuestro logo colaborando con sponsors, banderolas, adhesivos,etc. con empresas que se dediquen a actividades de ocio marítimas especialmente, así como en actividades lúdico-recreativas, regatas y competiciones náuticas pudiendo dar visibilidad al mayor publico de este sector

- Recursos: 
Poner al dia las plataformas digitales, como instagram, facebook, etc. y potenciando el plan de marketing mencionado anteriormente.

**Comment by 1987elo** [comment]
@ajsb85 tengo el contra briefing, con algunas ideas de mejora, espero sean útiles ;)

**Comment by vicktorinox** [comment]
@ajsb85 podemos tener a elo como nuestra IA ??? tiene buenas ideas.
