### ISSUE TITLE
Visual Identity Mockups

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#4]
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/a15b889f-df22-4211-b5aa-057c79790cf7)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/adb0a86e-622d-46ee-92a2-fdc6f51bf8cf)
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/dd0b83fc-a4b7-4213-8528-2ce8c0ec2e83)
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/77af898e-2d86-46d3-ab7b-feda4c74876e)

**Comment by 1987elo** [comment]
@ajsb85 a revisar, serian las propuestas de mockup's para el marketing de los nuevos logos

**Comment by vicktorinox** [comment]
@1987elo me gustan las dos primeras tazas de cafe la segunda un poco mas que la primera. Entro en conflicto aquí porque el primer logo me parece cool
