### ISSUE TITLE
Business Card

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#5]
https://github.com/bigblueinnova/press-kit/assets/150131187/2310c90d-2619-43ae-87fd-f0d40a24f62f
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/bfa50708-9fa5-411b-95d6-60f7ecb44608)

tarjeta de visita muy simple sólo con pagina web y logo

**Comment by 1987elo** [comment]
@ajsb85 mi idea de tarjeta, muy simple para nuevo posible logo

**Comment by vicktorinox** [comment]
@1987elo canvas dice debajo verdad? jeje Canvas was here... lol

**Comment by 1987elo** [comment]
@vicktorinox luego la mejoré, eran propuestas... ;P

**Comment by ajsb85** [comment]
Hola @vicktorinox 
Este es el diseño definitivo:

![image](https://github.com/bigblueinnova/press-kit/assets/663460/31987f1d-da07-48f2-9742-fdc2fd19f3b4)
