### ISSUE TITLE
PROS Logotype

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#7]
creo que es demasiado parecido al de microsoft edge 

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/3b0dc961-599a-47a9-8963-f9e610a2426f)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/8e5c9b15-56e7-4e38-8733-103ca32733e1)

**Comment by 1987elo** [comment]
@ajsb85 aquí sólo es un detalle, que me parece que tiene un aire al de Microsoft Edge, ya me dices

**Comment by vicktorinox** [comment]
@1987elo jejeje sip viendolo asi parece la copia del proyecto Edge de MS

**Comment by ajsb85** [comment]
Bueno, por lo menos estamos en la misma onda 🌊
