### ISSUE TITLE
Identity Coporate Manual

### ISSUE THREAD

**Issue by 1987elo** [bigblueinnova/press-kit#9]
![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/eea1d462-0189-4689-bf92-784c36339f91)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/060b17db-d4f1-465a-b697-7287ae5c5675)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/e6b77240-8e40-495e-bef4-faa37be3925e)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/4cea95e8-6f74-4b5c-8c20-31cdba1f3b41)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/79d428d3-c42a-4a6a-829c-99b04cd6a96a)

![Image](https://github.com/bigblueinnova/press-kit/assets/150131187/8f56a4ba-d591-409d-bdaa-ca0bfe6bfa42)

**Comment by vicktorinox** [comment]
@1987elo aprobado todo tu trabajo, super pro.
